language:
  python

python:
  - 3.7
  - 3.8

matrix:
  include:
    - env: TOXENV=lint

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - pip install --upgrade -e .[develop]
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: __token__
  password:
    secure: dcQBtD5nNhWxgnHHtmIjDd/oJO1heM4JOUwm4vdtJcftkwgCFBP4zaNM9F/LmzM07tx5pp4o819X4gyjHHdXr4mab3J4kcqalWWH99GYQAuVB2IyCb6i034klYkf9wNMbBbcmp1AdEX1MNujnJbXKfs14bp0pQtIa/YTmIHVV3O6ttPI4ZqDS38Y6MaLy3rrPAv8rm3JtpL62/g19lJTfgF+jR+7H4aGcwLs3R+N2rFlTFeR+7lMRCfBF+v+ZeQdi24Lc6EaQSpQocqQAofcrhwbLUrRoD4IyYlNueJ+kVdNBBf5pERKzHuLjvCBQy5Bub/Q6RTsQG0naBggQH37kP8bwcWWKrkg2LI1oDhZeHfmqHVaq/gXooiOmnCluQCk/nmgU6ETeA49uKjOTYQxlki8MmSXDQb2oV4uGgCLdr6V7fCNIDphzNYCHw0/KMhjP/mOxdjFEc4A0JehyVnwAhjTpCgEWaLiCpdkxVdlOTr3SZ7LEZjh1yzTSsNMK5P3KRNl3ishCeBP0i6jOW8WqVV3HQ+fTRu4MHyyi8F3BKjo2wsPaY+hWtVh1mZm8waD8CVdE0HejP8m9mUUOS/POs7QBwpXzUCqp4bt1wU4Y+A+JVo3qS2U7d23GlvJRqVSldNLwLi5Pp8bt0PUtky6aWqNhgYtp+8xCIx8UiRZQgU=
  skip_existing: true
  on:
    tags: true
